# Generated by Django 5.0.7 on 2024-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='rh',
        ),
        migrations.AddField(
            model_name='faculty',
            name='TL',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='per',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='remaining_TL',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='CL',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='RH',
            field=models.IntegerField(default=1),
        ),
    ]
